name: ppiflow
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
  - schrodinger
  - bioconda
  - ostrokach
  - anaconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.14
  - attr=2.5.1
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.2.25
  - cairo=1.18.4
  - certifi=2025.4.26
  - cuda-nvcc=12.1.66
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.7.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.13.3
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - glew=2.1.0
  - glib=2.84.0
  - glib-tools=2.84.0
  - glm=1.0.1
  - graphite2=1.3.14
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - harfbuzz=11.0.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - icu=75.1
  - krb5=1.21.3
  - lame=3.100
  - ld_impl_linux-64=2.40
  - libaec=1.1.3
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libcap=2.75
  - libclang-cpp20.1=20.1.7
  - libclang13=20.1.7
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.4
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libiconv=1.18
  - libjpeg-turbo=3.0.3
  - libllvm20=20.1.7
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.49
  - libpq=17.5
  - libsndfile=1.2.2
  - libsqlite=3.50.1
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.6
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzip=1.11.2
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - mpg123=1.32.9
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.4
  - nspr=4.36
  - nss=3.113
  - openldap=2.6.10
  - openssl=3.5.0
  - pcre2=10.44
  - pip=25.0
  - pixman=0.46.2
  - ply=3.11
  - pmw=2.0.1
  - pthread-stubs=0.3
  - pulseaudio-client=17.0
  - pymol-open-source=3.1.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.10.13
  - python_abi=3.10
  - qt-main=5.15.15
  - readline=8.2
  - setuptools=75.8.0
  - sip=6.7.12
  - snappy=1.2.1
  - sqlite=3.31.1
  - tk=8.6.13
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.5.0
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - biopython==1.83
      - biotite==1.0.1
      - biotraj==1.2.2
      - blessed==1.20.0
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.3.1
      - crcmod==1.7
      - cycler==0.12.1
      - decorator==5.2.1
      - deepspeed==0.16.4
      - deprecated==1.2.18
      - dm-tree==0.1.6
      - docker-pycreds==0.4.0
      - e3nn==0.5.6
      - easydict==1.13
      - einops==0.8.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fair-esm==2.0.0
      - filelock==3.13.1
      - fonttools==4.56.0
      - freesasa==2.2.1
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gemmi==0.6.5
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gpustat==1.1.1
      - gputil==1.4.0
      - graphviz==0.21
      - grpcio==1.72.1
      - hjson==3.1.0
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - icecream==2.1.4
      - idna==3.10
      - ihm==2.2
      - iniconfig==2.0.0
      - ipdb==0.13.13
      - ipython==8.34.0
      - ipywidgets==8.1.5
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - lightning==2.5.0.post0
      - lightning-utilities==0.14.0
      - markdown==3.8
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdtraj==1.10.3
      - ml-collections==1.0.0
      - modelcif==0.7
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - netcdf4==1.7.2
      - networkx==3.3
      - ninja==1.11.1.3
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - optree==0.14.1
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pdbeccdutils==0.8.5
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pptree==3.1
      - prompt-toolkit==3.0.50
      - propcache==0.3.0
      - protobuf==3.20.2
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py3dmol==2.4.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - --find-links https://data.pyg.org/whl/torch-2.3.0+cu121.html
      - pyg-lib==0.4.0+pt23cu121
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - rdkit==2023.3.1
      - requests==2.32.3
      - scikit-learn==1.2.2
      - scikit-learn-extra==0.3.0
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - submitit==1.5.3
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tmtools==0.2.0
      - tomli==2.2.1
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - torch==2.3.1+cu121
      - torch-cluster==1.6.3+pt23cu121
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt23cu121
      - torch-sparse==0.6.18+pt23cu121
      - torch-spline-conv==1.2.2+pt23cu121
      - torchaudio==2.3.1+cu121
      - torchmetrics==1.6.2
      - torchtyping==0.1.5
      - torchvision==0.18.1+cu121
      - torchviz==0.0.3
      - tos==2.8.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==2.3.1
      - typeguard==2.13.3
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - wandb==0.19.8
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - yarl==1.18.3
